//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceMetierGeneral {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMetierGeneral.IGeneralService")]
    public interface IGeneralService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/GetPhoneNumbersForAutoComplete", ReplyAction="http://tempuri.org/IGeneralService/GetPhoneNumbersForAutoCompleteResponse")]
        string[] GetPhoneNumbersForAutoComplete(int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/GetPhoneNumbersForAutoComplete", ReplyAction="http://tempuri.org/IGeneralService/GetPhoneNumbersForAutoCompleteResponse")]
        System.Threading.Tasks.Task<string[]> GetPhoneNumbersForAutoCompleteAsync(int limit);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGeneralServiceChannel : WindowsFormsApp1.ServiceMetierGeneral.IGeneralService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GeneralServiceClient : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceMetierGeneral.IGeneralService>, WindowsFormsApp1.ServiceMetierGeneral.IGeneralService {
        
        public GeneralServiceClient() {
        }
        
        public GeneralServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GeneralServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeneralServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeneralServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetPhoneNumbersForAutoComplete(int limit) {
            return base.Channel.GetPhoneNumbersForAutoComplete(limit);
        }
        
        public System.Threading.Tasks.Task<string[]> GetPhoneNumbersForAutoCompleteAsync(int limit) {
            return base.Channel.GetPhoneNumbersForAutoCompleteAsync(limit);
        }
    }
}
