//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.AllServiceMetier {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AllServiceMetier.IAllService")]
    public interface IAllService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllService/LoadAgenda", ReplyAction="http://tempuri.org/IAllService/LoadAgendaResponse")]
        MetierRvMedical.Model.Agenda[] LoadAgenda(System.DateTime datetoday);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllService/LoadAgenda", ReplyAction="http://tempuri.org/IAllService/LoadAgendaResponse")]
        System.Threading.Tasks.Task<MetierRvMedical.Model.Agenda[]> LoadAgendaAsync(System.DateTime datetoday);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllService/LoadCreneauxByDate", ReplyAction="http://tempuri.org/IAllService/LoadCreneauxByDateResponse")]
        System.Collections.Generic.Dictionary<string, object>[] LoadCreneauxByDate(System.DateTime dateRecherche);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllService/LoadCreneauxByDate", ReplyAction="http://tempuri.org/IAllService/LoadCreneauxByDateResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, object>[]> LoadCreneauxByDateAsync(System.DateTime dateRecherche);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllService/CreneauxByHoraire", ReplyAction="http://tempuri.org/IAllService/CreneauxByHoraireResponse")]
        System.Collections.Generic.Dictionary<string, object>[] CreneauxByHoraire(System.DateTime dateRecherche);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllService/CreneauxByHoraire", ReplyAction="http://tempuri.org/IAllService/CreneauxByHoraireResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, object>[]> CreneauxByHoraireAsync(System.DateTime dateRecherche);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllService/ListeTimeCreneau", ReplyAction="http://tempuri.org/IAllService/ListeTimeCreneauResponse")]
        int[] ListeTimeCreneau(System.DateTime dateRecherche);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllService/ListeTimeCreneau", ReplyAction="http://tempuri.org/IAllService/ListeTimeCreneauResponse")]
        System.Threading.Tasks.Task<int[]> ListeTimeCreneauAsync(System.DateTime dateRecherche);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllService/CreneauxByHoraireMedecin", ReplyAction="http://tempuri.org/IAllService/CreneauxByHoraireMedecinResponse")]
        System.Collections.Generic.Dictionary<string, object>[] CreneauxByHoraireMedecin(System.DateTime dateRecherche, int idMedecin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllService/CreneauxByHoraireMedecin", ReplyAction="http://tempuri.org/IAllService/CreneauxByHoraireMedecinResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, object>[]> CreneauxByHoraireMedecinAsync(System.DateTime dateRecherche, int idMedecin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllService/AddFirstUser", ReplyAction="http://tempuri.org/IAllService/AddFirstUserResponse")]
        bool AddFirstUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllService/AddFirstUser", ReplyAction="http://tempuri.org/IAllService/AddFirstUserResponse")]
        System.Threading.Tasks.Task<bool> AddFirstUserAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllService/CheckUser", ReplyAction="http://tempuri.org/IAllService/CheckUserResponse")]
        bool CheckUser(string identifiantinbd, string mdp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllService/CheckUser", ReplyAction="http://tempuri.org/IAllService/CheckUserResponse")]
        System.Threading.Tasks.Task<bool> CheckUserAsync(string identifiantinbd, string mdp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllService/CheckAdmin", ReplyAction="http://tempuri.org/IAllService/CheckAdminResponse")]
        bool CheckAdmin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllService/CheckAdmin", ReplyAction="http://tempuri.org/IAllService/CheckAdminResponse")]
        System.Threading.Tasks.Task<bool> CheckAdminAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllService/UserInformation", ReplyAction="http://tempuri.org/IAllService/UserInformationResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MetierRvMedical.Model.Medecin))]
        MetierRvMedical.Model.Utilisateur UserInformation(string identifiantinbd, string mdp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllService/UserInformation", ReplyAction="http://tempuri.org/IAllService/UserInformationResponse")]
        System.Threading.Tasks.Task<MetierRvMedical.Model.Utilisateur> UserInformationAsync(string identifiantinbd, string mdp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllService/GetPhoneNumbersForAutoComplete", ReplyAction="http://tempuri.org/IAllService/GetPhoneNumbersForAutoCompleteResponse")]
        string[] GetPhoneNumbersForAutoComplete(int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllService/GetPhoneNumbersForAutoComplete", ReplyAction="http://tempuri.org/IAllService/GetPhoneNumbersForAutoCompleteResponse")]
        System.Threading.Tasks.Task<string[]> GetPhoneNumbersForAutoCompleteAsync(int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllService/GetListSoins", ReplyAction="http://tempuri.org/IAllService/GetListSoinsResponse")]
        MetierRvMedical.Model.Soin[] GetListSoins();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllService/GetListSoins", ReplyAction="http://tempuri.org/IAllService/GetListSoinsResponse")]
        System.Threading.Tasks.Task<MetierRvMedical.Model.Soin[]> GetListSoinsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllService/GetListeGroupesSanguins", ReplyAction="http://tempuri.org/IAllService/GetListeGroupesSanguinsResponse")]
        MetierRvMedical.Model.GroupeSanguin[] GetListeGroupesSanguins();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllService/GetListeGroupesSanguins", ReplyAction="http://tempuri.org/IAllService/GetListeGroupesSanguinsResponse")]
        System.Threading.Tasks.Task<MetierRvMedical.Model.GroupeSanguin[]> GetListeGroupesSanguinsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllService/GetListePatients", ReplyAction="http://tempuri.org/IAllService/GetListePatientsResponse")]
        MetierRvMedical.Model.Patient[] GetListePatients();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllService/GetListePatients", ReplyAction="http://tempuri.org/IAllService/GetListePatientsResponse")]
        System.Threading.Tasks.Task<MetierRvMedical.Model.Patient[]> GetListePatientsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllService/AddPatient", ReplyAction="http://tempuri.org/IAllService/AddPatientResponse")]
        bool AddPatient(MetierRvMedical.Model.Patient patient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllService/AddPatient", ReplyAction="http://tempuri.org/IAllService/AddPatientResponse")]
        System.Threading.Tasks.Task<bool> AddPatientAsync(MetierRvMedical.Model.Patient patient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllService/UpdatePatient", ReplyAction="http://tempuri.org/IAllService/UpdatePatientResponse")]
        bool UpdatePatient(MetierRvMedical.Model.Patient patient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllService/UpdatePatient", ReplyAction="http://tempuri.org/IAllService/UpdatePatientResponse")]
        System.Threading.Tasks.Task<bool> UpdatePatientAsync(MetierRvMedical.Model.Patient patient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllService/RemovePatient", ReplyAction="http://tempuri.org/IAllService/RemovePatientResponse")]
        bool RemovePatient(MetierRvMedical.Model.Patient patient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllService/RemovePatient", ReplyAction="http://tempuri.org/IAllService/RemovePatientResponse")]
        System.Threading.Tasks.Task<bool> RemovePatientAsync(MetierRvMedical.Model.Patient patient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllService/ResearchPatient", ReplyAction="http://tempuri.org/IAllService/ResearchPatientResponse")]
        MetierRvMedical.Model.Patient ResearchPatient(string phoneNumberInput);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllService/ResearchPatient", ReplyAction="http://tempuri.org/IAllService/ResearchPatientResponse")]
        System.Threading.Tasks.Task<MetierRvMedical.Model.Patient> ResearchPatientAsync(string phoneNumberInput);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllService/AddCreneaux", ReplyAction="http://tempuri.org/IAllService/AddCreneauxResponse")]
        int AddCreneaux(MetierRvMedical.Model.Creneau creneau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllService/AddCreneaux", ReplyAction="http://tempuri.org/IAllService/AddCreneauxResponse")]
        System.Threading.Tasks.Task<int> AddCreneauxAsync(MetierRvMedical.Model.Creneau creneau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllService/AddRendezVous", ReplyAction="http://tempuri.org/IAllService/AddRendezVousResponse")]
        bool AddRendezVous(MetierRvMedical.Model.RendezVous rv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllService/AddRendezVous", ReplyAction="http://tempuri.org/IAllService/AddRendezVousResponse")]
        System.Threading.Tasks.Task<bool> AddRendezVousAsync(MetierRvMedical.Model.RendezVous rv);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAllServiceChannel : WindowsFormsApp1.AllServiceMetier.IAllService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AllServiceClient : System.ServiceModel.ClientBase<WindowsFormsApp1.AllServiceMetier.IAllService>, WindowsFormsApp1.AllServiceMetier.IAllService {
        
        public AllServiceClient() {
        }
        
        public AllServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AllServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AllServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AllServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MetierRvMedical.Model.Agenda[] LoadAgenda(System.DateTime datetoday) {
            return base.Channel.LoadAgenda(datetoday);
        }
        
        public System.Threading.Tasks.Task<MetierRvMedical.Model.Agenda[]> LoadAgendaAsync(System.DateTime datetoday) {
            return base.Channel.LoadAgendaAsync(datetoday);
        }
        
        public System.Collections.Generic.Dictionary<string, object>[] LoadCreneauxByDate(System.DateTime dateRecherche) {
            return base.Channel.LoadCreneauxByDate(dateRecherche);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, object>[]> LoadCreneauxByDateAsync(System.DateTime dateRecherche) {
            return base.Channel.LoadCreneauxByDateAsync(dateRecherche);
        }
        
        public System.Collections.Generic.Dictionary<string, object>[] CreneauxByHoraire(System.DateTime dateRecherche) {
            return base.Channel.CreneauxByHoraire(dateRecherche);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, object>[]> CreneauxByHoraireAsync(System.DateTime dateRecherche) {
            return base.Channel.CreneauxByHoraireAsync(dateRecherche);
        }
        
        public int[] ListeTimeCreneau(System.DateTime dateRecherche) {
            return base.Channel.ListeTimeCreneau(dateRecherche);
        }
        
        public System.Threading.Tasks.Task<int[]> ListeTimeCreneauAsync(System.DateTime dateRecherche) {
            return base.Channel.ListeTimeCreneauAsync(dateRecherche);
        }
        
        public System.Collections.Generic.Dictionary<string, object>[] CreneauxByHoraireMedecin(System.DateTime dateRecherche, int idMedecin) {
            return base.Channel.CreneauxByHoraireMedecin(dateRecherche, idMedecin);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, object>[]> CreneauxByHoraireMedecinAsync(System.DateTime dateRecherche, int idMedecin) {
            return base.Channel.CreneauxByHoraireMedecinAsync(dateRecherche, idMedecin);
        }
        
        public bool AddFirstUser() {
            return base.Channel.AddFirstUser();
        }
        
        public System.Threading.Tasks.Task<bool> AddFirstUserAsync() {
            return base.Channel.AddFirstUserAsync();
        }
        
        public bool CheckUser(string identifiantinbd, string mdp) {
            return base.Channel.CheckUser(identifiantinbd, mdp);
        }
        
        public System.Threading.Tasks.Task<bool> CheckUserAsync(string identifiantinbd, string mdp) {
            return base.Channel.CheckUserAsync(identifiantinbd, mdp);
        }
        
        public bool CheckAdmin() {
            return base.Channel.CheckAdmin();
        }
        
        public System.Threading.Tasks.Task<bool> CheckAdminAsync() {
            return base.Channel.CheckAdminAsync();
        }
        
        public MetierRvMedical.Model.Utilisateur UserInformation(string identifiantinbd, string mdp) {
            return base.Channel.UserInformation(identifiantinbd, mdp);
        }
        
        public System.Threading.Tasks.Task<MetierRvMedical.Model.Utilisateur> UserInformationAsync(string identifiantinbd, string mdp) {
            return base.Channel.UserInformationAsync(identifiantinbd, mdp);
        }
        
        public string[] GetPhoneNumbersForAutoComplete(int limit) {
            return base.Channel.GetPhoneNumbersForAutoComplete(limit);
        }
        
        public System.Threading.Tasks.Task<string[]> GetPhoneNumbersForAutoCompleteAsync(int limit) {
            return base.Channel.GetPhoneNumbersForAutoCompleteAsync(limit);
        }
        
        public MetierRvMedical.Model.Soin[] GetListSoins() {
            return base.Channel.GetListSoins();
        }
        
        public System.Threading.Tasks.Task<MetierRvMedical.Model.Soin[]> GetListSoinsAsync() {
            return base.Channel.GetListSoinsAsync();
        }
        
        public MetierRvMedical.Model.GroupeSanguin[] GetListeGroupesSanguins() {
            return base.Channel.GetListeGroupesSanguins();
        }
        
        public System.Threading.Tasks.Task<MetierRvMedical.Model.GroupeSanguin[]> GetListeGroupesSanguinsAsync() {
            return base.Channel.GetListeGroupesSanguinsAsync();
        }
        
        public MetierRvMedical.Model.Patient[] GetListePatients() {
            return base.Channel.GetListePatients();
        }
        
        public System.Threading.Tasks.Task<MetierRvMedical.Model.Patient[]> GetListePatientsAsync() {
            return base.Channel.GetListePatientsAsync();
        }
        
        public bool AddPatient(MetierRvMedical.Model.Patient patient) {
            return base.Channel.AddPatient(patient);
        }
        
        public System.Threading.Tasks.Task<bool> AddPatientAsync(MetierRvMedical.Model.Patient patient) {
            return base.Channel.AddPatientAsync(patient);
        }
        
        public bool UpdatePatient(MetierRvMedical.Model.Patient patient) {
            return base.Channel.UpdatePatient(patient);
        }
        
        public System.Threading.Tasks.Task<bool> UpdatePatientAsync(MetierRvMedical.Model.Patient patient) {
            return base.Channel.UpdatePatientAsync(patient);
        }
        
        public bool RemovePatient(MetierRvMedical.Model.Patient patient) {
            return base.Channel.RemovePatient(patient);
        }
        
        public System.Threading.Tasks.Task<bool> RemovePatientAsync(MetierRvMedical.Model.Patient patient) {
            return base.Channel.RemovePatientAsync(patient);
        }
        
        public MetierRvMedical.Model.Patient ResearchPatient(string phoneNumberInput) {
            return base.Channel.ResearchPatient(phoneNumberInput);
        }
        
        public System.Threading.Tasks.Task<MetierRvMedical.Model.Patient> ResearchPatientAsync(string phoneNumberInput) {
            return base.Channel.ResearchPatientAsync(phoneNumberInput);
        }
        
        public int AddCreneaux(MetierRvMedical.Model.Creneau creneau) {
            return base.Channel.AddCreneaux(creneau);
        }
        
        public System.Threading.Tasks.Task<int> AddCreneauxAsync(MetierRvMedical.Model.Creneau creneau) {
            return base.Channel.AddCreneauxAsync(creneau);
        }
        
        public bool AddRendezVous(MetierRvMedical.Model.RendezVous rv) {
            return base.Channel.AddRendezVous(rv);
        }
        
        public System.Threading.Tasks.Task<bool> AddRendezVousAsync(MetierRvMedical.Model.RendezVous rv) {
            return base.Channel.AddRendezVousAsync(rv);
        }
    }
}
