//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceMetierAuthentification {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Personne", Namespace="http://schemas.datacontract.org/2004/07/MetierRvMedical.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsFormsApp1.ServiceMetierAuthentification.Utilisateur))]
    public partial class Personne : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomPrenomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TELField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adresse {
            get {
                return this.AdresseField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresseField, value) != true)) {
                    this.AdresseField = value;
                    this.RaisePropertyChanged("Adresse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdU {
            get {
                return this.IdUField;
            }
            set {
                if ((this.IdUField.Equals(value) != true)) {
                    this.IdUField = value;
                    this.RaisePropertyChanged("IdU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomPrenom {
            get {
                return this.NomPrenomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomPrenomField, value) != true)) {
                    this.NomPrenomField = value;
                    this.RaisePropertyChanged("NomPrenom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TEL {
            get {
                return this.TELField;
            }
            set {
                if ((object.ReferenceEquals(this.TELField, value) != true)) {
                    this.TELField = value;
                    this.RaisePropertyChanged("TEL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Utilisateur", Namespace="http://schemas.datacontract.org/2004/07/MetierRvMedical.Model")]
    [System.SerializableAttribute()]
    public partial class Utilisateur : WindowsFormsApp1.ServiceMetierAuthentification.Personne {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdRoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotDePasseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsApp1.ServiceMetierAuthentification.Role RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string identifiantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> statutField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRole {
            get {
                return this.IdRoleField;
            }
            set {
                if ((this.IdRoleField.Equals(value) != true)) {
                    this.IdRoleField = value;
                    this.RaisePropertyChanged("IdRole");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MotDePasse {
            get {
                return this.MotDePasseField;
            }
            set {
                if ((object.ReferenceEquals(this.MotDePasseField, value) != true)) {
                    this.MotDePasseField = value;
                    this.RaisePropertyChanged("MotDePasse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsFormsApp1.ServiceMetierAuthentification.Role Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string identifiant {
            get {
                return this.identifiantField;
            }
            set {
                if ((object.ReferenceEquals(this.identifiantField, value) != true)) {
                    this.identifiantField = value;
                    this.RaisePropertyChanged("identifiant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> statut {
            get {
                return this.statutField;
            }
            set {
                if ((this.statutField.Equals(value) != true)) {
                    this.statutField = value;
                    this.RaisePropertyChanged("statut");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Role", Namespace="http://schemas.datacontract.org/2004/07/MetierRvMedical.Model")]
    [System.SerializableAttribute()]
    public partial class Role : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMetierAuthentification.IAuthentificationService")]
    public interface IAuthentificationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentificationService/AddFirstUser", ReplyAction="http://tempuri.org/IAuthentificationService/AddFirstUserResponse")]
        bool AddFirstUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentificationService/AddFirstUser", ReplyAction="http://tempuri.org/IAuthentificationService/AddFirstUserResponse")]
        System.Threading.Tasks.Task<bool> AddFirstUserAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentificationService/CheckUser", ReplyAction="http://tempuri.org/IAuthentificationService/CheckUserResponse")]
        bool CheckUser(string identifiantinbd, string mdp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentificationService/CheckUser", ReplyAction="http://tempuri.org/IAuthentificationService/CheckUserResponse")]
        System.Threading.Tasks.Task<bool> CheckUserAsync(string identifiantinbd, string mdp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentificationService/CheckAdmin", ReplyAction="http://tempuri.org/IAuthentificationService/CheckAdminResponse")]
        bool CheckAdmin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentificationService/CheckAdmin", ReplyAction="http://tempuri.org/IAuthentificationService/CheckAdminResponse")]
        System.Threading.Tasks.Task<bool> CheckAdminAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentificationService/UserInformation", ReplyAction="http://tempuri.org/IAuthentificationService/UserInformationResponse")]
        WindowsFormsApp1.ServiceMetierAuthentification.Utilisateur UserInformation(string identifiantinbd, string mdp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentificationService/UserInformation", ReplyAction="http://tempuri.org/IAuthentificationService/UserInformationResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceMetierAuthentification.Utilisateur> UserInformationAsync(string identifiantinbd, string mdp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthentificationServiceChannel : WindowsFormsApp1.ServiceMetierAuthentification.IAuthentificationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthentificationServiceClient : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceMetierAuthentification.IAuthentificationService>, WindowsFormsApp1.ServiceMetierAuthentification.IAuthentificationService {
        
        public AuthentificationServiceClient() {
        }
        
        public AuthentificationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthentificationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthentificationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthentificationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddFirstUser() {
            return base.Channel.AddFirstUser();
        }
        
        public System.Threading.Tasks.Task<bool> AddFirstUserAsync() {
            return base.Channel.AddFirstUserAsync();
        }
        
        public bool CheckUser(string identifiantinbd, string mdp) {
            return base.Channel.CheckUser(identifiantinbd, mdp);
        }
        
        public System.Threading.Tasks.Task<bool> CheckUserAsync(string identifiantinbd, string mdp) {
            return base.Channel.CheckUserAsync(identifiantinbd, mdp);
        }
        
        public bool CheckAdmin() {
            return base.Channel.CheckAdmin();
        }
        
        public System.Threading.Tasks.Task<bool> CheckAdminAsync() {
            return base.Channel.CheckAdminAsync();
        }
        
        public WindowsFormsApp1.ServiceMetierAuthentification.Utilisateur UserInformation(string identifiantinbd, string mdp) {
            return base.Channel.UserInformation(identifiantinbd, mdp);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceMetierAuthentification.Utilisateur> UserInformationAsync(string identifiantinbd, string mdp) {
            return base.Channel.UserInformationAsync(identifiantinbd, mdp);
        }
    }
}
